// src/Components/Projects/Projects.jsx
import React from 'react'
import IndividualProject from './IndividualProject'
import {motion} from 'framer-motion'

function Projects() {
  return (
    <div className='projectsContainer'>
      <motion.div initial={{x:-1500}} animate={{x:0}} transition={{duration:0.5,delay:0.1}}>
        <IndividualProject props={{title:"Mocha to Makai",languages:"Vuejs, Firestore, Tailwind, Vuex",
                                    about:["• Created a fullstack website to display my families recipies",
                                           "• Implemented authentication with Firestore and Local Storage"]}} />
      </motion.div>
      <motion.div initial={{x:-1500}} animate={{x:0}} transition={{duration:0.5,delay:0.4}}>
        <IndividualProject props={{title:"Automated Arbitrage",languages:"Python: Pandas, Numpy, Beatifulsoup, Selenium",
                                    about:["• Automated scraping of bookie odds from multiple US bookies",
                                    "• Created an algorithm to find opportunites of positive predicted value and calculate numerical values to maximize profit",
                                    "• Automated scripts to run on a heruku server"],github:"link"}} />
      </motion.div>
      <motion.div initial={{x:-1500}} animate={{x:0}} transition={{duration:0.5,delay:0.7}}>
        <IndividualProject props={{title:"Brain Hemorhhage Classification/Segmentation",languages:"Python: Pandas, Numpy, Tensorflow, Keras",
                                    about:["• Created a classification model with a 87% test accuracy and 83% validation accuracy",
                                    "• Created a segmentation model with a 82% training accuracy and 76% validation accuracy",
                                    "• Fine tuned hyperparamters to decrease model bias"],github:"link"}} />
      </motion.div>
      <motion.div initial={{x:-1500}} animate={{x:0}} transition={{duration:0.5,delay:1}}>
        <IndividualProject props={{title:"Portfolio Website",languages:"Javascript: React, Framer-Motion",
                                    about:["• Built a portfolio website to display current and past work",
                                    "• Currently on the third iteration with new features including animation and multipage",]
                                    ,github:"link"}} />
      </motion.div>
    </div>
  )
}

export default Projects

// src/components/Projects.vue
<template>
  <div class="flex flex-col w-full h-full">
    <div class="w-2/3 mx-auto">
    <div class="mt-16 text-6xl text-center mb-5"> Projects </div>
    <Project
        v-for="item in projects"
        class="mb-5 mx-auto"
        :ProjectName="item.ProjectName"
        :Tools="item.Tools"
        :Bullets="item.Bullets"
      />
    </div>
  </div>
</template>

<script>
import { ref, onMounted, onUnmounted } from "vue";
import Project from "./Reusable/Project.vue";

export default {
  components: {
    Project,
  },
  setup() {
    const projects = ref([
      {ProjectName:"Mocha to Makai",
        Tools:"Vuejs, Typescript, Firebase, Vuex",
        Bullets:["• Utilized Vue.js and Firestore to create a multipage website to archive family recipes", 
                "• Implemented authentication and local state with firebase and Vuex respectively",
        ]},
      {ProjectName:"Personal Portfolio", 
        Tools:"Vuejs, Typescript",
        Bullets:["• Built a portfolio website to display current and past work", 
                "• Used figma for prototyping to implement smooth UI/UX"
        ]}, 
      {ProjectName:"Automated Arbitrage",
        Tools:"Python: Pandas, Numpy, Beatifulsoup, Selenium",
        Bullets:["• Automated scraping of bookie odds from multiple US bookies", 
                "• Created an algorithm to find opportunites of positive predicted value and calculate numerical values to maximize profit",
                "• Automated scripts to run on a heruku server",
        ]},
      {ProjectName:"Brain Hemorhhage Classification/Segmentation", 
        Tools:"Python: Pandas, Numpy, Tensorflow, Keras",
        Bullets:["• Created a classification model with a 87% test accuracy and 83% validation accuracy", 
                "• Created a segmentation model with a 82% training accuracy and 76% validation accuracy",
                "• Fine tuned hyperparamters to decrease model bias",
        ]},
    ])
    return {projects};
  },
};
</script>
